version: 2

sources:
  - name: price_raw
    description: "Raw data loaded from GCS"
    tables:
      - name: price_events
        description: "Price events extracted by Scrapy spiders"
        columns:
          - name: product_id
            tests:
              - not_null
          - name: price
            tests:
              - not_null
          - name: site_name
            tests:
              - not_null
              - accepted_values:
                  values: ['jumia_ma', 'electroplanet']
          - name: scraped_at
            tests:
              - not_null
